[tool.poetry]
name = "ep_votes"
version = "0.1.0"
description = ""
authors = ["Till Prochaska <mail@tillprochaska.de>"]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.25.1"
unidecode = "^1.2.0"
flake8-black = "^0.2.1"
beautifulsoup4 = "^4.9.3"
lxml = "^4.6.3"
werkzeug = "^2.0.1"
sentry-sdk = {extras = ["flask"], version = "^1.3.0"}
python-dotenv = "^0.18.0"
coverage = "^5.5"
pytest-cov = "^2.12.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
flake8 = "^3.9.2"
black = "^21.6b0"
requests-mock = "^1.9.3"
mypy = "^0.812"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
